image: node:12

stages:
- build
- publish

build:
  stage: build
  only:
    - tags
  script:
    # build rapida-common
    - cd packages/rapida-common
    - npm install
    - npm run build
    # build rapida-physics
    - cd ../rapida-physics
    - npm install
    - npm run build
    # build rapida
    - cd ../rapida
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/rapida-common/lib/
      - packages/rapida-physics/lib/
      - packages/rapida/lib/
    expire_in: 1 day

publish:
  stage: publish
  only:
    - tags
  needs: 
    - build
  script:
    # publish rapida-physics
    - cd packages/rapida-physics
    - echo @rapidajs:registry=https://gitlab.com/api/v4/projects/29283145/packages/npm/ >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29283145/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish
    # publish rapida
    - cd ../rapida
    - echo @rapidajs:registry=https://gitlab.com/api/v4/projects/29283145/packages/npm/ >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29283145/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish

