image: node:14

stages:
- build
- publish

build:
  stage: build
  only:
    - main
    - merge_requests
  script:
    - yarn workspaces focus @rapidajs/rapida
    - (cd packages/rapida-common && yarn run build)
    - (cd packages/rapida-physics && yarn run build)
    - (cd packages/rapida && yarn run build)
    - npm run release
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit:
        - packages/rapida/junit.xml
        - packages/rapida-common/junit.xml
    paths:
      - node_modules/
      - packages/rapida-common/node_modules/
      - packages/rapida-physics/node_modules/
      - packages/rapida/node_modules/
      - packages/rapida-common/lib/
      - packages/rapida-physics/lib/
      - packages/rapida/lib/
    expire_in: 1 day

publish:
  stage: publish
  only:
    - main
  needs: 
    - build
  script:
    - yarn changeset publish --otp=$NPM_TOKEN
