image: node:14

stages:
- workflow

workflow:
  stage: workflow
  only:
    - merge_requests
  script:
    # install npm packages
    - yarn install
    # will build and test everything
    - yarn run release
    # - |- 
    #   if [[ $CI_COMMIT_BRANCH == "main" ]]; then
    #     # publish npm packages if on the main branch
    #     yarn dlx @changesets/cli@^2.18.1 publish --otp=$NPM_TOKEN
    #   fi
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

pages:
  stage: workflow
  needs:
    - workflow
  only:
    - main
  environment:
    name: Production
    url: "https://rapidajs.dev/"
  script:
    - yarn install
    # will build and test everything, including the website
    - yarn run release 
    - |- 
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        # copy @rapidajs/rapida-website files in place for gitlab pages
        mkdir public
        cp -r website/out/* public/
      fi
  artifacts:
    paths:
      - public
