image: node:14

stages:
- build
- test
- publish

build:
  stage: build
  only:
    - main
    - merge_requests
  script:
    # build rapida-common
    - cd packages/rapida-common
    - npm install
    - npm run build
    # build rapida-physics
    - cd ../rapida-physics
    - npm install
    - npm run build
    # build rapida
    - cd ../rapida
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/rapida-common/lib/
      - packages/rapida-physics/lib/
      - packages/rapida/lib/
    expire_in: 1 day

test:
  stage: test
  only:
    - main
    - merge_requests
  needs: 
    - build
  script:
    - npm run release

publish:
  stage: publish
  only:
    - main
  needs: 
    - build
  script:
    # publish rapida-physics
    - cd packages/rapida-physics
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish
    # publish rapida
    - cd ../rapida 
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish
