image: node:14

stages:
- workflow

workflow:
  stage: workflow
  only:
    - main
    - merge_requests
  script:
    # build npm packages
    - yarn workspaces focus @rapidajs/rapida-website
    - (cd packages/rapida-common && yarn run build)
    - (cd packages/postprocessing && yarn run build)
    - (cd packages/recs && yarn run build)
    - (cd packages/cannon-worker && yarn run build)
    - (cd packages/rapida && yarn run build)
    # will build and test all packages and build website
    - yarn run release
    # release if we are on the main branch
    - |- 
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        # publish npm packages if on the main branch
        # FIXME: there isn't a clear way of installing the root workspaces dependencies without installing all package dependencies.
        #        As a workaround, @changesets/cli is being run via yarn dlx with the same version as in the root package.json
        yarn dlx @changesets/cli@^2.18.1 publish --otp=$NPM_TOKEN
      fi
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

pages:
  stage: workflow
  needs:
    - workflow
  only:
    - main
  environment:
    name: Production
    url: "https://rapidajs.dev/"
  script:
    # includes @rapidajs/rapida-website, @rapidajs/rapida, @rapidajs/postprocessing, @rapidajs/recs, @rapidajs/cannon-worker and @rapidajs/rapida-common
    - yarn workspaces focus @rapidajs/rapida-website
    # build storybooks, generate docs, then build the nextjs static website
    - yarn website:build 
    - |- 
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        # copy @rapidajs/rapida-website files in place for gitlab pages
        mkdir public
        cp -r website/out/* public/
      fi
  artifacts:
    paths:
      - public
