image: node:12

stages:
- build
- publish

# Build common packages
build-common:
  stage: build
  only:
    - tags
  script:
    # build rapida-common
    - cd packages/rapida-common
    - npm install
    - npm run build
    # build rapida-physics
    - cd ../rapida-physics
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/rapida-common/lib/
      - packages/rapida-physics/lib/
    expire_in: 1 day

build-client:
  stage: build
  only:
    - tags
  needs:
    - build-common
  script:
    - cd packages/rapida
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/rapida/lib/
    expire_in: 1 day

build-server:
  stage: build
  only:
    - tags
  needs:
    - build-common
  script:
    - cd packages/rapida-server
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/rapida-server/lib/
    expire_in: 1 day

# Publish NPM packages
publish-physics:
  stage: publish
  only:
    - tags
  needs: 
    - build-common
  script:
    - cd packages/rapida-physics
    - echo @isaacmason:registry=https://gitlab.com/api/v4/projects/29283145/packages/npm/ >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29283145/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish

publish-client:
  stage: publish
  only:
    - tags
  needs: 
    - build-client
  script:
    - cd packages/rapida
    - echo @isaacmason:registry=https://gitlab.com/api/v4/projects/29283145/packages/npm/ >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29283145/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish

publish-server:
  stage: publish
  only:
    - tags
  needs: 
    - build-server
  script:
    - cd packages/rapida-server
    - echo @isaacmason:registry=https://gitlab.com/api/v4/projects/29283145/packages/npm/ >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29283145/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG --allow-same-version
    - npm publish
