image: node:14

stages:
- workflow

workflow:
  stage: workflow
  only:
    - main
    - merge_requests
  script:
    # build npm packages
    - yarn workspaces focus @rapidajs/rapida
    - (cd packages/rapida-common && yarn run build)
    - (cd packages/rapida-physics && yarn run build)
    - (cd packages/rapida && yarn run build)
    - npm run release
    # build the website
    # ...
    
    # publish npm packages if on the main branch
    - |- 
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        yarn ci-changesets-publish
      fi
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit:
        - packages/rapida/junit.xml
        - packages/rapida-common/junit.xml
    paths:
      - node_modules/
      - packages/rapida-common/node_modules/
      - packages/rapida-physics/node_modules/
      - packages/rapida/node_modules/
      - packages/rapida-common/lib/
      - packages/rapida-physics/lib/
      - packages/rapida/lib/
    expire_in: 1 day
