"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REMOVE_ENTITY_FROM_SCENE_EVENT_NAME = exports.ADD_ENTITY_TO_SCENE_EVENT_NAME = void 0;
var ADD_ENTITY_TO_SCENE_EVENT_NAME = 'scene.e.add';
exports.ADD_ENTITY_TO_SCENE_EVENT_NAME = ADD_ENTITY_TO_SCENE_EVENT_NAME;
var REMOVE_ENTITY_FROM_SCENE_EVENT_NAME = 'scene.e.remove';
exports.REMOVE_ENTITY_FROM_SCENE_EVENT_NAME = REMOVE_ENTITY_FROM_SCENE_EVENT_NAME;
